$axure.loadCurrentPage({
  "url":"订阅管理页.html",
  "generationDate":new Date(1397443654796.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg",
"tpcc_wz",
"tpcc_zt",
"tpcc_kd",
"L3"],
  "page":{
    "packageId":"362236e1761d45df92137fde19165da0",
    "type":"Axure:Page",
    "name":"订阅管理页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"528c261badde4d49a2370ce0ec31d27f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":128},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29a22e43c9e40368701d4fff4d38081",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":128},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"811ceb8c44234d7b89f61258ed3566d0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":154},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4fdf707d7d42ebbc33aee80b7e674c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":154},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c6cd9eec34ea44f0af9d0d654375ce34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4989F2},
            "location":{
              "x":470,
              "y":268},
            "size":{
              "width":120,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4C8EFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0880025cfd044d1a97d17e8cda5a5a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4989F2},
                "location":{
                  "x":470,
                  "y":268},
                "size":{
                  "width":120,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4C8EFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订阅管理页/u4.png"}},
{
          "id":"04462592dafe4d79a1dc272d1b5b6d7d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":100},
            "size":{
              "width":640,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订阅管理页/u6_line.png"}},
{
          "id":"6c1553f185ea4ac1be54846048561221",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":80},
            "size":{
              "width":86,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c3b92e22b44d7c8df3d4b5b2d40ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":80},
                "size":{
                  "width":86,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c938a8f8448f4c22b6c60b01cfbe8897",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":230,
              "y":80},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e686a9f1b0474f468ba20e8c12f45c54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":230,
                  "y":80},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b73bd7555dbb47a3a5b0d7c64cfc3b21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":128},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6410a83c93c8464dbce21f5931694a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":128},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ce5e77e8d8e40a0859105e07f8cbbb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":154},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ece06ee76f4435da1bdfd74435423be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":154},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f29cc888db6c44219e3560df0b20e8cd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":238},
            "size":{
              "width":640,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订阅管理页/u6_line.png"}},
{
          "id":"26032cec7e454bd88c04fefe53aa6090",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":180},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d406cbc77a084213b7f315a0f77bb973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":180},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f4fdf620b01a4ca49b0f4ea923ce1ec5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":206},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b12f9e98330a4abe9dea47938a688dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":206},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9913d19d2b22448080d2358ad73cf1b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":180},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1ba92c886848a598480d932744634a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":180},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80ae8819ddbc4e60a4b16ca506f9b74b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":206},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3827e33a145c467a969102d2a22f52bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":206},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce146d7ab81f46cfa8cd739f6485e122",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
            "fontSize":"14px",
            "size":{
              "width":1600,
              "height":32},
            "borderWidth":"-1",
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0cea2f9b0cc4b8abaa761ef5bd14646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
                "fontSize":"14px",
                "size":{
                  "width":1600,
                  "height":32},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页（单列）/u86.png"}},
{
          "id":"cfd83af1501a4135ba7bc9e71b0678fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":200,
              "y":0},
            "size":{
              "width":100,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0adc1104f683453e8ab735100d462f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页（单列）/u88.png"}},
{
          "id":"92f9344d4811476787b05c40e153f984",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Maiandra GD Bold', 'Maiandra GD'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":322,
              "y":0},
            "size":{
              "width":100,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1011f4fb930478692d3931908fbd0a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Maiandra GD Bold', 'Maiandra GD'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":322,
                  "y":0},
                "size":{
                  "width":100,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页（单列）/u88.png"}},
{
          "id":"14291a1d62184f8192eb7ec3a937706f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF4888EF},
            "location":{
              "x":330,
              "y":30},
            "size":{
              "width":84,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e4796249014a9480d4235cedb6c65a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4888EF},
                "location":{
                  "x":330,
                  "y":30},
                "size":{
                  "width":84,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订阅管理页/u30.png"}},
{
          "id":"de86f41c94f343738862003384130919",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4989F2,
              "opacity":1},
            "location":{
              "x":750,
              "y":0},
            "size":{
              "width":100,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19369144093345678595431d8e22681a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Maiandra GD Normal', 'Maiandra GD'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4989F2,
                  "opacity":1},
                "location":{
                  "x":750,
                  "y":0},
                "size":{
                  "width":100,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页（单列）/u88.png"}},
{
          "id":"d7d4553e3dfd4218b2a986856f3c68ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":27},
            "size":{
              "width":1600,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/搜索页（单列）/u96_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "528c261badde4d49a2370ce0ec31d27f":{
      "scriptId":"u0"},
    "b29a22e43c9e40368701d4fff4d38081":{
      "scriptId":"u1"},
    "811ceb8c44234d7b89f61258ed3566d0":{
      "scriptId":"u2"},
    "2a4fdf707d7d42ebbc33aee80b7e674c":{
      "scriptId":"u3"},
    "c6cd9eec34ea44f0af9d0d654375ce34":{
      "scriptId":"u4"},
    "0880025cfd044d1a97d17e8cda5a5a1c":{
      "scriptId":"u5"},
    "04462592dafe4d79a1dc272d1b5b6d7d":{
      "scriptId":"u6"},
    "6c1553f185ea4ac1be54846048561221":{
      "scriptId":"u7"},
    "70c3b92e22b44d7c8df3d4b5b2d40ae5":{
      "scriptId":"u8"},
    "c938a8f8448f4c22b6c60b01cfbe8897":{
      "scriptId":"u9"},
    "e686a9f1b0474f468ba20e8c12f45c54":{
      "scriptId":"u10"},
    "b73bd7555dbb47a3a5b0d7c64cfc3b21":{
      "scriptId":"u11"},
    "6410a83c93c8464dbce21f5931694a85":{
      "scriptId":"u12"},
    "8ce5e77e8d8e40a0859105e07f8cbbb4":{
      "scriptId":"u13"},
    "8ece06ee76f4435da1bdfd74435423be":{
      "scriptId":"u14"},
    "f29cc888db6c44219e3560df0b20e8cd":{
      "scriptId":"u15"},
    "26032cec7e454bd88c04fefe53aa6090":{
      "scriptId":"u16"},
    "d406cbc77a084213b7f315a0f77bb973":{
      "scriptId":"u17"},
    "f4fdf620b01a4ca49b0f4ea923ce1ec5":{
      "scriptId":"u18"},
    "b12f9e98330a4abe9dea47938a688dab":{
      "scriptId":"u19"},
    "9913d19d2b22448080d2358ad73cf1b8":{
      "scriptId":"u20"},
    "2c1ba92c886848a598480d932744634a":{
      "scriptId":"u21"},
    "80ae8819ddbc4e60a4b16ca506f9b74b":{
      "scriptId":"u22"},
    "3827e33a145c467a969102d2a22f52bf":{
      "scriptId":"u23"},
    "ce146d7ab81f46cfa8cd739f6485e122":{
      "scriptId":"u24"},
    "c0cea2f9b0cc4b8abaa761ef5bd14646":{
      "scriptId":"u25"},
    "cfd83af1501a4135ba7bc9e71b0678fd":{
      "scriptId":"u26"},
    "0adc1104f683453e8ab735100d462f1b":{
      "scriptId":"u27"},
    "92f9344d4811476787b05c40e153f984":{
      "scriptId":"u28"},
    "c1011f4fb930478692d3931908fbd0a2":{
      "scriptId":"u29"},
    "14291a1d62184f8192eb7ec3a937706f":{
      "scriptId":"u30"},
    "21e4796249014a9480d4235cedb6c65a":{
      "scriptId":"u31"},
    "de86f41c94f343738862003384130919":{
      "scriptId":"u32"},
    "19369144093345678595431d8e22681a":{
      "scriptId":"u33"},
    "d7d4553e3dfd4218b2a986856f3c68ee":{
      "scriptId":"u34"}}});